### ISSUE TITLE
asking for a login

### ISSUE THREAD

**Issue by theRoboticarm** [fforchino/vectorx#22]
in the stage between connecting and the 8080 web server on my raspberry pi it is asking me for a password for the epod even though there is not one

**Comment by fforchino** [comment]
Sorry but I don't understand the context. If you're talking about the installation flow of the VectorX Rpi4 image, as described in the setup instructions, when you boot the image the Rpi goes to hotspot mode, you must connect to it and enter the SSID and password for your home wifi network, so that it will reboot and connect to it...

**Comment by fforchino** [comment]
Don't open issues if you are uncertain of how it should work. Start a GitHub discussion instead.
